### ISSUE TITLE
你好，同款HP600G1 我在选择网卡的时候遇到一些问题，请求你的帮助

### ISSUE THREAD

**Issue by marchocode** [LomotHo/Hackintosh-600g1-DM-4670t#2]
您好，非常感谢您分享的efi
我这里和你同款的HP600G1,本人小白，第一次安装黑苹果，在选择网卡的时候购买遇到问题，
bcm943224pciebt2 这一款网卡是苹果拆机网卡吗？能否直接安装到HP600G1 或者需要转接器

**Comment by LomotHo** [comment]
需要转接头，600g1主板上的是ngff（m.2）接口，你需要一个苹果网卡转ngff的转接卡

**Comment by marchocode** [comment]
非常感谢
